dist: trusty
sudo: false
language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
  email:
    secure: nPx+zn/fwO7bccczFVyR6htucmgPotH4M8yhsQcTgMXMtIFtTmgh146GNahZsqEoB062TlZSHChvRN2PhgCaczUh5zxjgosv9+AKBcandZHAzaPpRf1qDfOH4QvJozynwPqVmPll2YCFrV70bSH/TdGUPLJQDwFMmd/EL7/UEmFtb4mBzU3e0zWGNZEgy6uScXC/iSwFn6AzqU32Efc+xyOxWHNvRQwIJGvgvhXtYoEoa8B6ew4kFoY9P6wNfmz1IEQsah/FbYbPz8UgALcryNo8XY01bRkDDGVr/6GIrp6z+ZDcghi4Ib+oOKJLMaN2lyQv+++zH+UmicrSZqi3nDM0v0wuLvp1Qt901faoD55Khr5LMzLJndbVA1bxHqHDMif9E20HilXjG60miFd+R662IW0Bp2P8tGXq26oI4d7AJ+f+2y66Yeem/RVdMOIrbluR2HdlQzYvdhRVcGjrRGN7XBUaP34+iGdOgt6uYVIPKI9OZtzAPCHs72YUah09QhWl6eMsXTLwfB7imISBSer94Jyx+/WN+X2HCJLBTsVPVejxppihLl+IASkLhxoqjSXqNcP5tkx+GLDWKv85Im1i+swgr6AdPrN4gXI8vAIIxDhgBYYoZkqiEHiTBQrmzhDPjnx8DDIPT4oCvGFRNxOWz0PQDNV3RuvyRDNTlOo=
  api_key:
    secure: RFA0hcOLVf/YPA3oEP3GqJDjfOjdUyyXZIsoBinxQpPRcHSOPqGlDwNQDy1JtlaFvN3uAR5U187dqEyey+H8lkZfoTATdhZGhODjmDaRYHlLrEUFGCalhX68vyOX9s1D16n0aK49H+8qmNQs3LEcf3O8NleWLAMWf729I1lyHdOA5kiD3ygOse6toawHM37HGkHjBIc29BgiRzQxgWdLG2s/vRsEizLh0f6UONahLIqPO38H/k1GxICijUPahjZHuwjvrdh22JJLgRlRSyr98xNyMoKB6TN/DqSG3hrStB6T0HY0U4qWhdsXcWV98i/OXTHAlxnWOoXCziB+gvQt8dbf3EKw645ZXtjOqQ6lGUMJFctssq6bhIXiPLYcN36xVYzYtWehWZdRRwCh+cnnlNQadXucE0aBrED3SJxQu7uzkgBcOAjGLZDcMBFtOMGbnN9RzsvbkPVLiqx5DkiV3/p0jmmWXG5AEfe8iGhmEO9HOJNG3+JstAsPQWAFPeerqmSIOSqSmyZ4tidLpoCRyGdF3Uyy3Hj4diwPCVUS3iqUu5JH2o9Or+Mnh9fCVWXHH+bxy2V9i2PY2rsy9RPG4bESKHgx/9JmOYkQSEwTVQQtRTw5JsX1oYpOz6+dd0+fwhqRdYNFk8Hy7Ls/EbQljsuuRgEy9nd/Y/AQyxeC8AA=
